name: <%= params.extensionName %> PHP

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@main
    with:
      enable_backend_testing: <%= modules.backendTesting %>

      backend_directory: <%= params.backendDirectory %>
