name: JS

on: [workflow_dispatch, push, pull_request]

# The reusable workflow definitions will be moved to the `flarum/framework` repo soon.
# This will break your current script.
# When this happens, run `flarum-cli audit infra --fix` to update your infrastructure.

jobs:
  run:
    uses: flarum/.github/.github/workflows/REUSABLE_frontend.yml@main
    with:
      enable_bundlewatch: <%= modules.bundlewatch %>
      enable_prettier: <%= modules.prettier %>
      enable_typescript: <%= modules.typescript %> 

      frontend_directory: <%= frontend_directory %>
      main_git_branch: <%= mainGitBranch %>
    secrets:
      bundlewatch_github_token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}